// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjojyzvulhvqeitnaenv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqb2p5enZ1bGh2cWVpdG5hZW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5ODc2MzIsImV4cCI6MjA4NzU2MzYzMn0._Dxrh7K_-e1TGRE82V71nxPcXCP_xu4y7brDSyNdiHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});